name: Deploy Interactive Feedback MCP Server

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn
    
    - name: Test server
      run: |
        python -c "
        import sys
        sys.path.append('.')
        try:
            from railway_server import app
            print('✅ Server imports successfully')
        except Exception as e:
            print(f'❌ Server import failed: {e}')
            sys.exit(1)
        "
    
    - name: Deployment Status
      run: |
        echo "✅ Interactive Feedback MCP Server test passed!"
        echo "📋 Ready for manual deployment to:"
        echo "   - Railway: https://railway.app"
        echo "   - Render: https://render.com"
        echo "   - Heroku: https://heroku.com"
